config/routes.rb
Rails.application.routes.draw do

 devise_for :users

 resources :products do
   resources :comments
 end
 resources :orders, only: [:index, :show, :create, :destroy]
 resources :users
 
 resources :payments

  post 'payments/create'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static/pages'

  get 'static/about'

  get 'static/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'
  
  resources :orders, only: [:index, :show, :create, :destroy]

    root 'static_pages#landing_page'

    mount ActionCable.server => '/cable'

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  has_many :orders
  has_many :comments
  
  validates :name, :price, :image_url, :colour, presence: true
	validates :price, numericality: true
  
  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
	# TODO 1:
	# Add another before filter here for the new, create, edit, update, and destroy actions
  # Make sure that the user is logged in and/or logged in AND admin (you can just redirect_to root_url otherwise
	# Remember how the RESTful actions work- the new method in the controller just refers to the product creation view, 
	# But create is the action for sending that request to the server

	# TODO 2:
	# Go into the individual views and place if statements around the links to each action
	# E.G. Think about it, why would you have a link to the show action which would only redirect a non admin user?


	# GET /products
  # GET /products.json
  def index
    if params[:q]
    search_term = params[:q]
    @products = Product.where("name LIKE ?", "%#{search_term}%")
  else
    @products = Product.all.paginate(:page => params[:page], :per_page => 12)

    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to "/products", notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
  <% @comments.each do |comment| %>
    <div class="row">
      <hr>
        <p>
          <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
          <% if signed_in? && current_user.admin? %>
          <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </p>
      <p><%= "Rating: #{comment.rating}/5" %></p>
      <div class="rated" data-score="<%= comment.rating %>"></div>
      <p><%= comment.body %></p>
      </div>
  <% end %>
</div>

app/views/products/_form.html.erb
<div class="wrapper">
  <%= form_for(@product) do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
        <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, step: 0.01, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :colour %><br>
    <%= f.text_field :colour, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
<div class="container-fluid" id="prod-show">
	<div class="row">
		<div class="col-md-12 col-xs-12">
      <h4>Add a review:</h4>
  			<%= form_for([@product, @product.comments.build], remote: true) do |f| %>
		      <p>
		      <%= f.label :body, "Comments" %><br>
		      <%= f.text_area :body %>
		    </p>
		    
		    <p>
		      <div class="rating"></div>
		    </p>
		    
		    <p>
		      <%= f.submit "Submit", class: "btn btn-primary" %>
		    </p>
			<% end %>
    </div>
  </div>
</div>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 product-images">
      <%= link_to image_tag(product.image_url, class: "img-responsive"), product%>
        <h3 class="product-name"><%= product.name %></h3>
        <p><%= product.description %></p>
        <strong>$<%= product.price %></strong><br />
      <br>
      <%= link_to 'New Product', new_product_path %>
      <%= link_to 'Edit', edit_product_path(product) %>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div><!-- /col -->
  </div>
</div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1 class="title">Recent Products</h1>
<% cache(cache_key_for_products) do %>
  <%= render @products %>
<% end %>
    
    
    

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div id="content">
  <div class="container-fluid">
	  <div class="row">
		  <div class="col-md-12 col-xs-12">
		  <% cache @product do %>
	        <h1 class="title"><%= @product.name %></h4>
	      <% end %>
	
	      <div class="image"><%= image_tag(@product.image_url, class: "img-responsive img-zoom", data_zoom_image: @product.image_url) %></div>
	
	    </div>
	  </div>
	</div>
	
  <div class="container-fluid">
	  <div class="row">
		  <div class="col-md-12 col-xs-12">
		    
		    <h3>Description</h3>
	      <p class="description"><%= @product.description %></p>
	
	      <h3>Price</h3>
	      <p class="price"><%= number_to_currency(@product.price) %></p>

	      <h3>Colour</h3>
	      <p class="colour"><%= @product.colour %></p>
	      
	     </div>
	  </div>
	</div>


   <%= form_tag "/payments/create" do %>
   <%= render partial: "shared/stripe_checkout_button" %>
   <% end %>

<%= render 'new_comment' %>
<%= render 'comments' %>
<div class="alert alert-info" style="display: none" role="alert">A new comment was posted!</div>

<p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div> </p>


</p>
      </div>
	  </div>
	</div>

</div>
<%= will_paginate @comments %>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to "Delete Product", product_path(@product), method: :delete, data: { confirm: "Are you sure?" } %>