config/routes.rb
Rails.application.routes.draw do

 devise_for :users

 resources :products do
   resources :comments
 end
 resources :orders, only: [:index, :show, :create, :destroy]
 resources :users
 
 resources :payments

  post 'payments/create'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static/pages'

  get 'static/about'

  get 'static/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'
  
  resources :orders, only: [:index, :show, :create, :destroy]

    root 'static_pages#landing_page'

    mount ActionCable.server => '/cable'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Berlin Bikes</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  
  <link href="https://fonts.googleapis.com/css?family=Lobster|Oswald" rel="stylesheet">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <%= action_cable_meta_tag %>
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  
</head>
<body>
  <% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
<% end %>
  <% if alert %>
    <p id="alert" class="alert alert-danger"><%= alert %></p>
<% end %>
    <div class="navbar-border">
      <div class="container-fluid">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Berlin Bikes</a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">

              
              <li><%= link_to "About", static_pages_about_path(@about) %></li>
              <li><%= link_to "Contact", static_pages_contact_path(@contact) %></li>
              <li><%= link_to "Products", products_path %></li>
            </ul>
            
            <ul class="nav pull-right log-style">
              <li>
                <% if user_signed_in? %>
                  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                <% else %>
                  <%= link_to('Login', new_user_session_path) %>
                <% end %>
              </li>
            </ul>
            
            <div id="search">
					      <%= form_tag("/products", method: "get") do %>
						      <%= label_tag(:q, "Search:", id: "srch-color") %>
						      <%= text_field_tag(:q) %>
						      <%= submit_tag("Search") %>
					      <% end %>
					</div>
            
            
            
          
          </div><!--/.nav-collapse -->
        </div><!-- end nav container --> 
        </nav><!-- end nav  -->
      </div>
  
  <%= yield %>

  <!-- footer -->
    <footer class="container">
      <div class="copyright-footer">
        <p>&copy; Maxx Alexander - 2016</p>
      </div>
    </footer><!-- /footer -->
</body>
</html>